Appium test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,121 +1,121 @@
-# name: Build APK and IPA
+name: Build APK and IPA
 
-# on:
-#   push:
-#     branches: [ "main" ]
+on:
+  push:
+    branches: [ "main" ]
 
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
-#     strategy:
-#       matrix:
-#         api-level: [34]
-#     steps:
-#       - uses: actions/checkout@v3  # Checkout repository
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        api-level: [34]
+    steps:
+      - uses: actions/checkout@v3  # Checkout repository
 
-#       - name: Use Node.js
-#         uses: actions/setup-node@v3
-#         with:
-#           node-version: '20.x'
-#           cache: 'yarn'
+      - name: Use Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20.x'
+          cache: 'yarn'
 
-#       - name: Install dependencies
-#         run: yarn
+      - name: Install dependencies
+        run: yarn
 
-#       - name: Set Up JDK
-#         uses: actions/setup-java@v3
-#         with:
-#           distribution: 'zulu'
-#           java-version: '17'
-#           cache: 'gradle'
+      - name: Set Up JDK
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: '17'
+          cache: 'gradle'
 
-#       - name: Set up Android SDK
-#         uses: android-actions/setup-android@v3
-#         with:
-#           api-level: 34
-#           build-tools: 34.0.0
-#           target: 'google_apis'
-#           arch: 'x86_64'
+      - name: Set up Android SDK
+        uses: android-actions/setup-android@v3
+        with:
+          api-level: 34
+          build-tools: 34.0.0
+          target: 'google_apis'
+          arch: 'x86_64'
 
-#       - name: Make gradlew executable
-#         run: chmod +x ./android/gradlew
+      - name: Make gradlew executable
+        run: chmod +x ./android/gradlew
 
-#       - name: Clean project
-#         run: ./gradlew clean
-#         working-directory: ./android
+      - name: Clean project
+        run: ./gradlew clean
+        working-directory: ./android
 
-#       - name: Build APK
-#         run: ./gradlew assembleRelease --stacktrace
-#         working-directory: ./android
+      - name: Build APK
+        run: ./gradlew assembleRelease --stacktrace
+        working-directory: ./android
 
-#       - name: Find APK files
-#         run: find . -name "*.apk" -print
+      - name: Find APK files
+        run: find . -name "*.apk" -print
 
-#       - name: List APK files
-#         run: ls -R android/app/build/outputs/apk/release
+      - name: List APK files
+        run: ls -R android/app/build/outputs/apk/release
 
-#       - name: Add Android SDK to PATH
-#         run: echo "${{ steps.setup-android.outputs.android-home }}/cmdline-tools/latest/bin" >> $GITHUB_PATH
+      - name: Add Android SDK to PATH
+        run: echo "${{ steps.setup-android.outputs.android-home }}/cmdline-tools/latest/bin" >> $GITHUB_PATH
 
-#       - name: Start Emulator
-#         uses: ReactiveCircus/android-emulator-runner@v2
-#         with:
-#           api-level: 34
-#           target: default
-#           arch: x86_64
-#           profile: Pixel_4
-#           emulator-options: "-no-window -no-boot-anim"
-#           disable-animations: true
-#           emulator-boot-timeout: 900  # Increase boot timeout if needed
+      - name: Start Emulator
+        uses: ReactiveCircus/android-emulator-runner@v2
+        with:
+          api-level: 34
+          target: default
+          arch: x86_64
+          profile: Pixel_4
+          emulator-options: "-no-window -no-boot-anim"
+          disable-animations: true
+          emulator-boot-timeout: 900  # Increase boot timeout if needed
 
-#       - name: List ADB Devices
-#         run: adb devices
+      - name: List ADB Devices
+        run: adb devices
 
-#       - name: Wait for Emulator to Start
-#         run: |
-#           adb wait-for-device
-#           adb shell getprop sys.boot_completed  # Check boot completion status
+      - name: Wait for Emulator to Start
+        run: |
+          adb wait-for-device
+          adb shell getprop sys.boot_completed  # Check boot completion status
 
-#       - name: Check Emulator Boot Status
-#         run: |
-#           boot_status=$(adb shell getprop sys.boot_completed)
-#           if [ "$boot_status" -ne 1 ]; then
-#             echo "Emulator boot failed: $boot_status"
-#             exit 1
-#           fi
+      - name: Check Emulator Boot Status
+        run: |
+          boot_status=$(adb shell getprop sys.boot_completed)
+          if [ "$boot_status" -ne 1 ]; then
+            echo "Emulator boot failed: $boot_status"
+            exit 1
+          fi
 
-#       - name: Get Emulator Logs
-#         run: adb logcat -d
+      - name: Get Emulator Logs
+        run: adb logcat -d
 
-#       # Install Appium
-#       - name: Install Appium
-#         run: npm install -g appium
+      # Install Appium
+      - name: Install Appium
+        run: npm install -g appium
 
-#       # Run Appium Server
-#       - name: Start Appium Server
-#         run: |
-#           appium &  # Run Appium server in the background
-#           sleep 10  # Wait for the server to start
+      # Run Appium Server
+      - name: Start Appium Server
+        run: |
+          appium &  # Run Appium server in the background
+          sleep 10  # Wait for the server to start
 
-#       - name: Run Appium Tests
-#         run: |
-#           npm run test:e2e
+      - name: Run Appium Tests
+        run: |
+          npm run test:e2e
 
-#       - name: Kill Emulator
-#         if: always()
-#         run: |
-#           if adb devices | grep -q emulator; then
-#             adb -s emulator-5554 emu kill || echo "Failed to kill emulator"
-#           else
-#             echo "Emulator is not running"
-#           fi
+      - name: Kill Emulator
+        if: always()
+        run: |
+          if adb devices | grep -q emulator; then
+            adb -s emulator-5554 emu kill || echo "Failed to kill emulator"
+          else
+            echo "Emulator is not running"
+          fi
 
-#       - name: Upload APK Release
-#         if: success()
-#         uses: actions/upload-artifact@v3
-#         with:
-#           name: Apk release generated
-#           path: android/app/build/outputs/apk/release
+      - name: Upload APK Release
+        if: success()
+        uses: actions/upload-artifact@v3
+        with:
+          name: Apk release generated
+          path: android/app/build/outputs/apk/release
 
 
 
@@ -205,51 +205,53 @@
 #         name: test-results
 #         path: target/surefire-reports # Update the path to where your test results are stored
 
-name: Android Emulator with Appium
 
-on:
-  push:
-    branches:
-      - main
 
-jobs:
-  test-apk:
-    runs-on: ubuntu-latest
+# name: Android Emulator with Appium
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+# on:
+#   push:
+#     branches:
+#       - main
 
-    - name: Set up JDK
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
+# jobs:
+#   test-apk:
+#     runs-on: ubuntu-latest
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '20.x'
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v3
 
-    - name: Install dependencies
-      run: npm install
+#     - name: Set up JDK
+#       uses: actions/setup-java@v3
+#       with:
+#         java-version: '17'
 
-    - name: Install Android system image
-      run: sdkmanager "system-images;android-30;default;x86_64"
+#     - name: Set up Node.js
+#       uses: actions/setup-node@v3
+#       with:
+#         node-version: '20.x'
 
-    - name: Update SDK Tools
-      run: sdkmanager --update
+#     - name: Install dependencies
+#       run: npm install
 
-    - name: Set up Android SDK
-      uses: reactivecircus/android-emulator-runner@v3
-      with:
-        api-level: 30
-        target: default
-        arch: x86_64
-        profile: Nexus_5X
-        emulator-options: '-no-window -gpu swiftshader_indirect'
+#     - name: Install Android system image
+#       run: sdkmanager "system-images;android-30;default;x86_64"
 
-    - name: Start Android emulator
-      run: |
-        adb start-server
-        adb devices
-        adb shell input keyevent 82
+#     - name: Update SDK Tools
+#       run: sdkmanager --update
+
+#     - name: Set up Android SDK
+#       uses: reactivecircus/android-emulator-runner@v3
+#       with:
+#         api-level: 30
+#         target: default
+#         arch: x86_64
+#         profile: Nexus_5X
+#         emulator-options: '-no-window -gpu swiftshader_indirect'
+
+#     - name: Start Android emulator
+#       run: |
+#         adb start-server
+#         adb devices
+#         adb shell input keyevent 82
