Build apk and iIp

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -66,8 +66,11 @@ jobs:
           profile: Pixel_4
           emulator-options: "-no-window -no-boot-anim"
           disable-animations: true
-          emulator-build: 'stable'
+          emulator-build: 'latest'
           boot-timeout: 600
+
+      - name: List ADB Devices
+        run: adb devices
 
       - name: Wait for Emulator to Start
         run: adb wait-for-device
@@ -85,7 +88,7 @@ jobs:
         if: always()
         run: |
           if adb devices | grep -q emulator; then
-            adb -s emulator-5554 emu kill
+            adb -s emulator-5554 emu kill || echo "Failed to kill emulator"
           else
             echo "Emulator is not running"
           fi
